// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUpgradeRules implements UpgradeRuleInterface
type FakeUpgradeRules struct {
	Fake *FakeSqlV1beta2
	ns   string
}

var upgraderulesResource = schema.GroupVersionResource{Group: "sql.databases", Version: "v1beta2", Resource: "upgraderules"}

var upgraderulesKind = schema.GroupVersionKind{Group: "sql.databases", Version: "v1beta2", Kind: "UpgradeRule"}

// Get takes name of the upgradeRule, and returns the corresponding upgradeRule object, and an error if there is any.
func (c *FakeUpgradeRules) Get(name string, options v1.GetOptions) (result *v1beta2.UpgradeRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(upgraderulesResource, c.ns, name), &v1beta2.UpgradeRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeRule), err
}

// List takes label and field selectors, and returns the list of UpgradeRules that match those selectors.
func (c *FakeUpgradeRules) List(opts v1.ListOptions) (result *v1beta2.UpgradeRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(upgraderulesResource, upgraderulesKind, c.ns, opts), &v1beta2.UpgradeRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.UpgradeRuleList{ListMeta: obj.(*v1beta2.UpgradeRuleList).ListMeta}
	for _, item := range obj.(*v1beta2.UpgradeRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested upgradeRules.
func (c *FakeUpgradeRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(upgraderulesResource, c.ns, opts))

}

// Create takes the representation of a upgradeRule and creates it.  Returns the server's representation of the upgradeRule, and an error, if there is any.
func (c *FakeUpgradeRules) Create(upgradeRule *v1beta2.UpgradeRule) (result *v1beta2.UpgradeRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(upgraderulesResource, c.ns, upgradeRule), &v1beta2.UpgradeRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeRule), err
}

// Update takes the representation of a upgradeRule and updates it. Returns the server's representation of the upgradeRule, and an error, if there is any.
func (c *FakeUpgradeRules) Update(upgradeRule *v1beta2.UpgradeRule) (result *v1beta2.UpgradeRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(upgraderulesResource, c.ns, upgradeRule), &v1beta2.UpgradeRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeRule), err
}

// Delete takes name of the upgradeRule and deletes it. Returns an error if one occurs.
func (c *FakeUpgradeRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(upgraderulesResource, c.ns, name), &v1beta2.UpgradeRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpgradeRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(upgraderulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta2.UpgradeRuleList{})
	return err
}

// Patch applies the patch and returns the patched upgradeRule.
func (c *FakeUpgradeRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(upgraderulesResource, c.ns, name, data, subresources...), &v1beta2.UpgradeRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeRule), err
}
