// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGaleras implements GaleraInterface
type FakeGaleras struct {
	Fake *FakeSqlV1beta2
	ns   string
}

var galerasResource = schema.GroupVersionResource{Group: "sql.databases", Version: "v1beta2", Resource: "galeras"}

var galerasKind = schema.GroupVersionKind{Group: "sql.databases", Version: "v1beta2", Kind: "Galera"}

// Get takes name of the galera, and returns the corresponding galera object, and an error if there is any.
func (c *FakeGaleras) Get(name string, options v1.GetOptions) (result *v1beta2.Galera, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(galerasResource, c.ns, name), &v1beta2.Galera{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.Galera), err
}

// List takes label and field selectors, and returns the list of Galeras that match those selectors.
func (c *FakeGaleras) List(opts v1.ListOptions) (result *v1beta2.GaleraList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(galerasResource, galerasKind, c.ns, opts), &v1beta2.GaleraList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.GaleraList{ListMeta: obj.(*v1beta2.GaleraList).ListMeta}
	for _, item := range obj.(*v1beta2.GaleraList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested galeras.
func (c *FakeGaleras) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(galerasResource, c.ns, opts))

}

// Create takes the representation of a galera and creates it.  Returns the server's representation of the galera, and an error, if there is any.
func (c *FakeGaleras) Create(galera *v1beta2.Galera) (result *v1beta2.Galera, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(galerasResource, c.ns, galera), &v1beta2.Galera{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.Galera), err
}

// Update takes the representation of a galera and updates it. Returns the server's representation of the galera, and an error, if there is any.
func (c *FakeGaleras) Update(galera *v1beta2.Galera) (result *v1beta2.Galera, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(galerasResource, c.ns, galera), &v1beta2.Galera{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.Galera), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGaleras) UpdateStatus(galera *v1beta2.Galera) (*v1beta2.Galera, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galerasResource, "status", c.ns, galera), &v1beta2.Galera{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.Galera), err
}

// Delete takes name of the galera and deletes it. Returns an error if one occurs.
func (c *FakeGaleras) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(galerasResource, c.ns, name), &v1beta2.Galera{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGaleras) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(galerasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta2.GaleraList{})
	return err
}

// Patch applies the patch and returns the patched galera.
func (c *FakeGaleras) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.Galera, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(galerasResource, c.ns, name, pt, data, subresources...), &v1beta2.Galera{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.Galera), err
}

// GetScale takes name of the galera, and returns the corresponding scale object, and an error if there is any.
func (c *FakeGaleras) GetScale(galeraName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceAction(galerasResource, c.ns, "scale", galeraName), &autoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *FakeGaleras) UpdateScale(galeraName string, scale *autoscalingv1.Scale) (result *autoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(galerasResource, "scale", c.ns, scale), &autoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.Scale), err
}
