// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUpgradeConfigs implements UpgradeConfigInterface
type FakeUpgradeConfigs struct {
	Fake *FakeSqlV1beta2
	ns   string
}

var upgradeconfigsResource = schema.GroupVersionResource{Group: "sql.databases", Version: "v1beta2", Resource: "upgradeconfigs"}

var upgradeconfigsKind = schema.GroupVersionKind{Group: "sql.databases", Version: "v1beta2", Kind: "UpgradeConfig"}

// Get takes name of the upgradeConfig, and returns the corresponding upgradeConfig object, and an error if there is any.
func (c *FakeUpgradeConfigs) Get(name string, options v1.GetOptions) (result *v1beta2.UpgradeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(upgradeconfigsResource, c.ns, name), &v1beta2.UpgradeConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeConfig), err
}

// List takes label and field selectors, and returns the list of UpgradeConfigs that match those selectors.
func (c *FakeUpgradeConfigs) List(opts v1.ListOptions) (result *v1beta2.UpgradeConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(upgradeconfigsResource, upgradeconfigsKind, c.ns, opts), &v1beta2.UpgradeConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.UpgradeConfigList{ListMeta: obj.(*v1beta2.UpgradeConfigList).ListMeta}
	for _, item := range obj.(*v1beta2.UpgradeConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested upgradeConfigs.
func (c *FakeUpgradeConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(upgradeconfigsResource, c.ns, opts))

}

// Create takes the representation of a upgradeConfig and creates it.  Returns the server's representation of the upgradeConfig, and an error, if there is any.
func (c *FakeUpgradeConfigs) Create(upgradeConfig *v1beta2.UpgradeConfig) (result *v1beta2.UpgradeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(upgradeconfigsResource, c.ns, upgradeConfig), &v1beta2.UpgradeConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeConfig), err
}

// Update takes the representation of a upgradeConfig and updates it. Returns the server's representation of the upgradeConfig, and an error, if there is any.
func (c *FakeUpgradeConfigs) Update(upgradeConfig *v1beta2.UpgradeConfig) (result *v1beta2.UpgradeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(upgradeconfigsResource, c.ns, upgradeConfig), &v1beta2.UpgradeConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeConfig), err
}

// Delete takes name of the upgradeConfig and deletes it. Returns an error if one occurs.
func (c *FakeUpgradeConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(upgradeconfigsResource, c.ns, name), &v1beta2.UpgradeConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpgradeConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(upgradeconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta2.UpgradeConfigList{})
	return err
}

// Patch applies the patch and returns the patched upgradeConfig.
func (c *FakeUpgradeConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(upgradeconfigsResource, c.ns, name, data, subresources...), &v1beta2.UpgradeConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeConfig), err
}
