// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"
	scheme "galera-operator/pkg/client/clientset/versioned/scheme"
	"time"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GalerasGetter has a method to return a GaleraInterface.
// A group's client should implement this interface.
type GalerasGetter interface {
	Galeras(namespace string) GaleraInterface
}

// GaleraInterface has methods to work with Galera resources.
type GaleraInterface interface {
	Create(*v1beta2.Galera) (*v1beta2.Galera, error)
	Update(*v1beta2.Galera) (*v1beta2.Galera, error)
	UpdateStatus(*v1beta2.Galera) (*v1beta2.Galera, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta2.Galera, error)
	List(opts v1.ListOptions) (*v1beta2.GaleraList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.Galera, err error)
	GetScale(galeraName string, options v1.GetOptions) (*autoscalingv1.Scale, error)
	UpdateScale(galeraName string, scale *autoscalingv1.Scale) (*autoscalingv1.Scale, error)

	GaleraExpansion
}

// galeras implements GaleraInterface
type galeras struct {
	client rest.Interface
	ns     string
}

// newGaleras returns a Galeras
func newGaleras(c *SqlV1beta2Client, namespace string) *galeras {
	return &galeras{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the galera, and returns the corresponding galera object, and an error if there is any.
func (c *galeras) Get(name string, options v1.GetOptions) (result *v1beta2.Galera, err error) {
	result = &v1beta2.Galera{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galeras").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Galeras that match those selectors.
func (c *galeras) List(opts v1.ListOptions) (result *v1beta2.GaleraList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.GaleraList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galeras").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested galeras.
func (c *galeras) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("galeras").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a galera and creates it.  Returns the server's representation of the galera, and an error, if there is any.
func (c *galeras) Create(galera *v1beta2.Galera) (result *v1beta2.Galera, err error) {
	result = &v1beta2.Galera{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("galeras").
		Body(galera).
		Do().
		Into(result)
	return
}

// Update takes the representation of a galera and updates it. Returns the server's representation of the galera, and an error, if there is any.
func (c *galeras) Update(galera *v1beta2.Galera) (result *v1beta2.Galera, err error) {
	result = &v1beta2.Galera{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galeras").
		Name(galera.Name).
		Body(galera).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *galeras) UpdateStatus(galera *v1beta2.Galera) (result *v1beta2.Galera, err error) {
	result = &v1beta2.Galera{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galeras").
		Name(galera.Name).
		SubResource("status").
		Body(galera).
		Do().
		Into(result)
	return
}

// Delete takes name of the galera and deletes it. Returns an error if one occurs.
func (c *galeras) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galeras").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *galeras) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("galeras").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched galera.
func (c *galeras) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.Galera, err error) {
	result = &v1beta2.Galera{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("galeras").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}

// GetScale takes name of the galera, and returns the corresponding autoscalingv1.Scale object, and an error if there is any.
func (c *galeras) GetScale(galeraName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("galeras").
		Name(galeraName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// UpdateScale takes the top resource name and the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *galeras) UpdateScale(galeraName string, scale *autoscalingv1.Scale) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("galeras").
		Name(galeraName).
		SubResource("scale").
		Body(scale).
		Do().
		Into(result)
	return
}
