// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"
	scheme "galera-operator/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UpgradeRulesGetter has a method to return a UpgradeRuleInterface.
// A group's client should implement this interface.
type UpgradeRulesGetter interface {
	UpgradeRules(namespace string) UpgradeRuleInterface
}

// UpgradeRuleInterface has methods to work with UpgradeRule resources.
type UpgradeRuleInterface interface {
	Create(*v1beta2.UpgradeRule) (*v1beta2.UpgradeRule, error)
	Update(*v1beta2.UpgradeRule) (*v1beta2.UpgradeRule, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta2.UpgradeRule, error)
	List(opts v1.ListOptions) (*v1beta2.UpgradeRuleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeRule, err error)
	UpgradeRuleExpansion
}

// upgradeRules implements UpgradeRuleInterface
type upgradeRules struct {
	client rest.Interface
	ns     string
}

// newUpgradeRules returns a UpgradeRules
func newUpgradeRules(c *SqlV1beta2Client, namespace string) *upgradeRules {
	return &upgradeRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the upgradeRule, and returns the corresponding upgradeRule object, and an error if there is any.
func (c *upgradeRules) Get(name string, options v1.GetOptions) (result *v1beta2.UpgradeRule, err error) {
	result = &v1beta2.UpgradeRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgraderules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UpgradeRules that match those selectors.
func (c *upgradeRules) List(opts v1.ListOptions) (result *v1beta2.UpgradeRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.UpgradeRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgraderules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested upgradeRules.
func (c *upgradeRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("upgraderules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a upgradeRule and creates it.  Returns the server's representation of the upgradeRule, and an error, if there is any.
func (c *upgradeRules) Create(upgradeRule *v1beta2.UpgradeRule) (result *v1beta2.UpgradeRule, err error) {
	result = &v1beta2.UpgradeRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("upgraderules").
		Body(upgradeRule).
		Do().
		Into(result)
	return
}

// Update takes the representation of a upgradeRule and updates it. Returns the server's representation of the upgradeRule, and an error, if there is any.
func (c *upgradeRules) Update(upgradeRule *v1beta2.UpgradeRule) (result *v1beta2.UpgradeRule, err error) {
	result = &v1beta2.UpgradeRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("upgraderules").
		Name(upgradeRule.Name).
		Body(upgradeRule).
		Do().
		Into(result)
	return
}

// Delete takes name of the upgradeRule and deletes it. Returns an error if one occurs.
func (c *upgradeRules) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgraderules").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *upgradeRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgraderules").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched upgradeRule.
func (c *upgradeRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeRule, err error) {
	result = &v1beta2.UpgradeRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("upgraderules").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
