// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	v1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"
	scheme "galera-operator/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UpgradeConfigsGetter has a method to return a UpgradeConfigInterface.
// A group's client should implement this interface.
type UpgradeConfigsGetter interface {
	UpgradeConfigs(namespace string) UpgradeConfigInterface
}

// UpgradeConfigInterface has methods to work with UpgradeConfig resources.
type UpgradeConfigInterface interface {
	Create(*v1beta2.UpgradeConfig) (*v1beta2.UpgradeConfig, error)
	Update(*v1beta2.UpgradeConfig) (*v1beta2.UpgradeConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta2.UpgradeConfig, error)
	List(opts v1.ListOptions) (*v1beta2.UpgradeConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeConfig, err error)
	UpgradeConfigExpansion
}

// upgradeConfigs implements UpgradeConfigInterface
type upgradeConfigs struct {
	client rest.Interface
	ns     string
}

// newUpgradeConfigs returns a UpgradeConfigs
func newUpgradeConfigs(c *SqlV1beta2Client, namespace string) *upgradeConfigs {
	return &upgradeConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the upgradeConfig, and returns the corresponding upgradeConfig object, and an error if there is any.
func (c *upgradeConfigs) Get(name string, options v1.GetOptions) (result *v1beta2.UpgradeConfig, err error) {
	result = &v1beta2.UpgradeConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UpgradeConfigs that match those selectors.
func (c *upgradeConfigs) List(opts v1.ListOptions) (result *v1beta2.UpgradeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.UpgradeConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested upgradeConfigs.
func (c *upgradeConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a upgradeConfig and creates it.  Returns the server's representation of the upgradeConfig, and an error, if there is any.
func (c *upgradeConfigs) Create(upgradeConfig *v1beta2.UpgradeConfig) (result *v1beta2.UpgradeConfig, err error) {
	result = &v1beta2.UpgradeConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		Body(upgradeConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a upgradeConfig and updates it. Returns the server's representation of the upgradeConfig, and an error, if there is any.
func (c *upgradeConfigs) Update(upgradeConfig *v1beta2.UpgradeConfig) (result *v1beta2.UpgradeConfig, err error) {
	result = &v1beta2.UpgradeConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		Name(upgradeConfig.Name).
		Body(upgradeConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the upgradeConfig and deletes it. Returns an error if one occurs.
func (c *upgradeConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *upgradeConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("upgradeconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched upgradeConfig.
func (c *upgradeConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta2.UpgradeConfig, err error) {
	result = &v1beta2.UpgradeConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("upgradeconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
