// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"galera-backup/pkg/models"
)

// GetStateByNameOKCode is the HTTP code returned for type GetStateByNameOK
const GetStateByNameOKCode int = 200

/*GetStateByNameOK running/completed or failed backup/restore

swagger:response getStateByNameOK
*/
type GetStateByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetStateByNameOK creates GetStateByNameOK with default headers values
func NewGetStateByNameOK() *GetStateByNameOK {

	return &GetStateByNameOK{}
}

// WithPayload adds the payload to the get state by name o k response
func (o *GetStateByNameOK) WithPayload(payload *models.Response) *GetStateByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get state by name o k response
func (o *GetStateByNameOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStateByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStateByNameDefault unknown state : not managed by this server

swagger:response getStateByNameDefault
*/
type GetStateByNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetStateByNameDefault creates GetStateByNameDefault with default headers values
func NewGetStateByNameDefault(code int) *GetStateByNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStateByNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get state by name default response
func (o *GetStateByNameDefault) WithStatusCode(code int) *GetStateByNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get state by name default response
func (o *GetStateByNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get state by name default response
func (o *GetStateByNameDefault) WithPayload(payload *models.Response) *GetStateByNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get state by name default response
func (o *GetStateByNameDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStateByNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
