// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"galera-backup/pkg/models"
)

// GetS3BackupOKCode is the HTTP code returned for type GetS3BackupOK
const GetS3BackupOKCode int = 200

/*GetS3BackupOK restore scheduled

swagger:response getS3BackupOK
*/
type GetS3BackupOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetS3BackupOK creates GetS3BackupOK with default headers values
func NewGetS3BackupOK() *GetS3BackupOK {

	return &GetS3BackupOK{}
}

// WithPayload adds the payload to the get s3 backup o k response
func (o *GetS3BackupOK) WithPayload(payload *models.Response) *GetS3BackupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get s3 backup o k response
func (o *GetS3BackupOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetS3BackupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetS3BackupDefault default ko response

swagger:response getS3BackupDefault
*/
type GetS3BackupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetS3BackupDefault creates GetS3BackupDefault with default headers values
func NewGetS3BackupDefault(code int) *GetS3BackupDefault {
	if code <= 0 {
		code = 500
	}

	return &GetS3BackupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get s3 backup default response
func (o *GetS3BackupDefault) WithStatusCode(code int) *GetS3BackupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get s3 backup default response
func (o *GetS3BackupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get s3 backup default response
func (o *GetS3BackupDefault) WithPayload(payload *models.Response) *GetS3BackupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get s3 backup default response
func (o *GetS3BackupDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetS3BackupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
