// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"galera-backup/pkg/models"
)

// GetProbeOKCode is the HTTP code returned for type GetProbeOK
const GetProbeOKCode int = 200

/*GetProbeOK running probe

swagger:response getProbeOK
*/
type GetProbeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetProbeOK creates GetProbeOK with default headers values
func NewGetProbeOK() *GetProbeOK {

	return &GetProbeOK{}
}

// WithPayload adds the payload to the get probe o k response
func (o *GetProbeOK) WithPayload(payload *models.Response) *GetProbeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get probe o k response
func (o *GetProbeOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProbeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
