// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetS3BackupHandlerFunc turns a function with the right signature into a get s3 backup handler
type GetS3BackupHandlerFunc func(GetS3BackupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetS3BackupHandlerFunc) Handle(params GetS3BackupParams) middleware.Responder {
	return fn(params)
}

// GetS3BackupHandler interface for that can handle valid get s3 backup params
type GetS3BackupHandler interface {
	Handle(GetS3BackupParams) middleware.Responder
}

// NewGetS3Backup creates a new http.Handler for the get s3 backup operation
func NewGetS3Backup(ctx *middleware.Context, handler GetS3BackupHandler) *GetS3Backup {
	return &GetS3Backup{Context: ctx, Handler: handler}
}

/*GetS3Backup swagger:route GET /s3 getS3Backup

Copy an existing backup from the provided S3 bucket

restore from S3 storage

*/
type GetS3Backup struct {
	Context *middleware.Context
	Handler GetS3BackupHandler
}

func (o *GetS3Backup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetS3BackupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
