// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"galera-backup/pkg/models"
)

// NewGetS3BackupParams creates a new GetS3BackupParams object
// no default values defined in spec.
func NewGetS3BackupParams() GetS3BackupParams {

	return GetS3BackupParams{}
}

// GetS3BackupParams contains all the bound params for the get s3 backup operation
// typically these are obtained from a http.Request
//
// swagger:parameters getS3Backup
type GetS3BackupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*backup location and credentials
	  Required: true
	  In: body
	*/
	S3 *models.S3
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetS3BackupParams() beforehand.
func (o *GetS3BackupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.S3
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("s3", "body"))
			} else {
				res = append(res, errors.NewParseError("s3", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.S3 = &body
			}
		}
	} else {
		res = append(res, errors.Required("s3", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
