// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProbeHandlerFunc turns a function with the right signature into a get probe handler
type GetProbeHandlerFunc func(GetProbeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProbeHandlerFunc) Handle(params GetProbeParams) middleware.Responder {
	return fn(params)
}

// GetProbeHandler interface for that can handle valid get probe params
type GetProbeHandler interface {
	Handle(GetProbeParams) middleware.Responder
}

// NewGetProbe creates a new http.Handler for the get probe operation
func NewGetProbe(ctx *middleware.Context, handler GetProbeHandler) *GetProbe {
	return &GetProbe{Context: ctx, Handler: handler}
}

/*GetProbe swagger:route GET /probe getProbe

Probe path used to monitor the process

*/
type GetProbe struct {
	Context *middleware.Context
	Handler GetProbeHandler
}

func (o *GetProbe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProbeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
