// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1beta2

import (
	apigalerav1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"
	versioned "galera-operator/pkg/client/clientset/versioned"
	internalinterfaces "galera-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta2 "galera-operator/pkg/client/listers/apigalera/v1beta2"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GaleraBackupInformer provides access to a shared informer and lister for
// GaleraBackups.
type GaleraBackupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta2.GaleraBackupLister
}

type galeraBackupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGaleraBackupInformer constructs a new informer for GaleraBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGaleraBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGaleraBackupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGaleraBackupInformer constructs a new informer for GaleraBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGaleraBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta2().GaleraBackups(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta2().GaleraBackups(namespace).Watch(options)
			},
		},
		&apigalerav1beta2.GaleraBackup{},
		resyncPeriod,
		indexers,
	)
}

func (f *galeraBackupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGaleraBackupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *galeraBackupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apigalerav1beta2.GaleraBackup{}, f.defaultInformer)
}

func (f *galeraBackupInformer) Lister() v1beta2.GaleraBackupLister {
	return v1beta2.NewGaleraBackupLister(f.Informer().GetIndexer())
}
