// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1beta2

import (
	apigalerav1beta2 "galera-operator/pkg/apis/apigalera/v1beta2"
	versioned "galera-operator/pkg/client/clientset/versioned"
	internalinterfaces "galera-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta2 "galera-operator/pkg/client/listers/apigalera/v1beta2"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GaleraInformer provides access to a shared informer and lister for
// Galeras.
type GaleraInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta2.GaleraLister
}

type galeraInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGaleraInformer constructs a new informer for Galera type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGaleraInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGaleraInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGaleraInformer constructs a new informer for Galera type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGaleraInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta2().Galeras(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SqlV1beta2().Galeras(namespace).Watch(options)
			},
		},
		&apigalerav1beta2.Galera{},
		resyncPeriod,
		indexers,
	)
}

func (f *galeraInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGaleraInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *galeraInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apigalerav1beta2.Galera{}, f.defaultInformer)
}

func (f *galeraInformer) Lister() v1beta2.GaleraLister {
	return v1beta2.NewGaleraLister(f.Informer().GetIndexer())
}
