// Copyright 2020 Orange SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1beta2

import (
	internalinterfaces "galera-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Galeras returns a GaleraInformer.
	Galeras() GaleraInformer
	// GaleraBackups returns a GaleraBackupInformer.
	GaleraBackups() GaleraBackupInformer
	// UpgradeConfigs returns a UpgradeConfigInformer.
	UpgradeConfigs() UpgradeConfigInformer
	// UpgradeRules returns a UpgradeRuleInformer.
	UpgradeRules() UpgradeRuleInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Galeras returns a GaleraInformer.
func (v *version) Galeras() GaleraInformer {
	return &galeraInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GaleraBackups returns a GaleraBackupInformer.
func (v *version) GaleraBackups() GaleraBackupInformer {
	return &galeraBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UpgradeConfigs returns a UpgradeConfigInformer.
func (v *version) UpgradeConfigs() UpgradeConfigInformer {
	return &upgradeConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UpgradeRules returns a UpgradeRuleInformer.
func (v *version) UpgradeRules() UpgradeRuleInformer {
	return &upgradeRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
