// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Galera Backup Tool
//
//  This is a backup server used for galera-operator project. You can find out more about galera-operator at [https://github.com/orange-opensource/galera-operator](https://github.com/orange-opensource/galera-operator)
//  Terms Of Service:
//    https://github.com/orange-opensource/galera-operator
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
