// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a backup server used for galera-operator project. You can find out more about galera-operator at [https://github.com/orange-opensource/galera-operator](https://github.com/orange-opensource/galera-operator)",
    "title": "Galera Backup Tool",
    "termsOfService": "https://github.com/orange-opensource/galera-operator",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/probe": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Probe path used to monitor the process",
        "operationId": "getProbe",
        "responses": {
          "200": {
            "description": "running probe",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/s3": {
      "get": {
        "description": "restore from S3 storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Copy an existing backup from the provided S3 bucket",
        "operationId": "getS3Backup",
        "parameters": [
          {
            "description": "backup location and credentials",
            "name": "s3",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/s3"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "restore scheduled",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "default ko response",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      },
      "post": {
        "description": "backup to S3 storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Add a new backup to the provided S3 bucket",
        "operationId": "addS3Backup",
        "parameters": [
          {
            "description": "backup location and credentials",
            "name": "s3",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/s3"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "backup scheduled",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "default ko response",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/state/{name}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Check the state of the provided backup or restore",
        "operationId": "getStateByName",
        "parameters": [
          {
            "type": "string",
            "description": "Name of a backup or restore operation",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "running/completed or failed backup/restore",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "unknown state : not managed by this server",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Response": {
      "type": "object",
      "required": [
        "status",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "s3": {
      "type": "object",
      "required": [
        "endpoint",
        "bucket",
        "accessKey",
        "secretKey",
        "backupName",
        "backupDir"
      ],
      "properties": {
        "accessKey": {
          "type": "string"
        },
        "backupDir": {
          "type": "string"
        },
        "backupName": {
          "type": "string"
        },
        "bucket": {
          "type": "string",
          "example": "galera"
        },
        "endpoint": {
          "type": "string",
          "example": "https://s3.dev.orange:8443"
        },
        "forcePathStyle": {
          "type": "boolean",
          "default": true
        },
        "region": {
          "type": "string",
          "default": "us-east-1",
          "example": "us-east-1"
        },
        "secretKey": {
          "type": "string"
        }
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about galera-operator",
    "url": "https://github.com/orange-opensource/galera-operator"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a backup server used for galera-operator project. You can find out more about galera-operator at [https://github.com/orange-opensource/galera-operator](https://github.com/orange-opensource/galera-operator)",
    "title": "Galera Backup Tool",
    "termsOfService": "https://github.com/orange-opensource/galera-operator",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/probe": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Probe path used to monitor the process",
        "operationId": "getProbe",
        "responses": {
          "200": {
            "description": "running probe",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/s3": {
      "get": {
        "description": "restore from S3 storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Copy an existing backup from the provided S3 bucket",
        "operationId": "getS3Backup",
        "parameters": [
          {
            "description": "backup location and credentials",
            "name": "s3",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/s3"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "restore scheduled",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "default ko response",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      },
      "post": {
        "description": "backup to S3 storage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Add a new backup to the provided S3 bucket",
        "operationId": "addS3Backup",
        "parameters": [
          {
            "description": "backup location and credentials",
            "name": "s3",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/s3"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "backup scheduled",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "default ko response",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    },
    "/state/{name}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Check the state of the provided backup or restore",
        "operationId": "getStateByName",
        "parameters": [
          {
            "type": "string",
            "description": "Name of a backup or restore operation",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "running/completed or failed backup/restore",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "unknown state : not managed by this server",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Response": {
      "type": "object",
      "required": [
        "status",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "s3": {
      "type": "object",
      "required": [
        "endpoint",
        "bucket",
        "accessKey",
        "secretKey",
        "backupName",
        "backupDir"
      ],
      "properties": {
        "accessKey": {
          "type": "string"
        },
        "backupDir": {
          "type": "string"
        },
        "backupName": {
          "type": "string"
        },
        "bucket": {
          "type": "string",
          "example": "galera"
        },
        "endpoint": {
          "type": "string",
          "example": "https://s3.dev.orange:8443"
        },
        "forcePathStyle": {
          "type": "boolean",
          "default": true
        },
        "region": {
          "type": "string",
          "default": "us-east-1",
          "example": "us-east-1"
        },
        "secretKey": {
          "type": "string"
        }
      }
    }
  },
  "externalDocs": {
    "description": "Find out more about galera-operator",
    "url": "https://github.com/orange-opensource/galera-operator"
  }
}`))
}
